name: comment_git_diff

on:
  workflow_dispatch:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging
    types: opened

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create comments
      run: |
        git log --reverse --no-merges --pretty=format:"- %s" master..test | cat >> comments


    - name: Post multi-line comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"$(cat comments)\"}" \
             ${URL}

