name: comment_git_diff

on:
  push:
  pull_request:
    branches:
      - master
      - staging
    types: opened
# git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF}
# git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }}
env:
    TARGET_BRANCH: ${{ github.base_ref }}

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create comments
      run: |
        git log --reverse --no-merges --pretty=format:"- %s" ${TARGET_BRANCH}..${{ github.event.before }}

    - name: Post multi-line comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"$(cat comments)\"}" \
             ${URL}

