name: comment_git_diff

on:
  pull_request:
    branches:
      - master
      - staging
    types: opened

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create comments
      run: |
        git log --reverse --no-merges --pretty=format:"- %s" ${{ github.event.pull_request.base.sha }}..${{ github.event.after }} >> comments
        sed -i -z 's/\n/\\n/g' comments

    - name: Post multi-line comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"$(cat comments)\"}" \
             ${{ github.event.pull_request.comments_url }}

