name: job-flow-test
on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Diff Action
        uses: technote-space/get-diff-action@v1.2.8
        with:
          SUFFIX_FILTER: .test
      - run: echo '${{ steps.git_diff.outputs.count }}'
      - run: echo OK
        if: ${{ steps.git_diff.outputs.count > 0}}

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello'

