name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{github.ref}}
    - run: echo 'branch is master'
      if: github.ref == 'refs/heads/master'
    - run: echo 'branch is not master'
      if: github.ref != 'refs/heads/master'
