name: test
on: push

jobs:
  repository-dispatch:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{github.ref}}
    - run: echo hello
      if: github.ref == 'refs/heads/master'
    #   - name: Repository Dispatch
    #     uses: peter-evans/repository-dispatch@v1.1.0
    #     with:
    #       token: ${{ secrets.REPO_ACCESS_TOKEN }}
    #       repository: naoyaUda/laravel-tweet-ddd
    #       event-type: deploy
    #       client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
